In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
import joblib

In [13]:
from sklearn.model_selection import KFold

In [14]:
conf_model = joblib.load("../data/large/conf.pkl")

In [15]:
conf_model

{'rows_train': 275565, 'ngrams': 44937, 'punct': 32}

In [21]:
output = [1 for i in range(conf_model['rows_train'])]

In [22]:
len(output)

275565

In [23]:
for train_index, test_index in KFold(n_splits=5).split(output):
    print(train_index, test_index)

[ 55113  55114  55115 ... 275562 275563 275564] [    0     1     2 ... 55110 55111 55112]
[     0      1      2 ... 275562 275563 275564] [ 55113  55114  55115 ... 110223 110224 110225]
[     0      1      2 ... 275562 275563 275564] [110226 110227 110228 ... 165336 165337 165338]
[     0      1      2 ... 275562 275563 275564] [165339 165340 165341 ... 220449 220450 220451]
[     0      1      2 ... 220449 220450 220451] [220452 220453 220454 ... 275562 275563 275564]


In [6]:
cv = KFold(n_splits=10, random_state=1, shuffle=True)

TypeError: 'KFold' object is not subscriptable

In [24]:
#path_training_small = "../data/pan20-authorship-verification-training-small.jsonl"

In [25]:
#df_texts = pd.read_json(path_training_small, lines=True)

In [26]:
#df_1000 = df_texts.sample(frac=1).reset_index(drop=True)[:10000]

In [27]:
#df_1000.to_json("../data/predict.jsonl", orient='records', lines=True)

In [28]:
path_answers = "../data/truncate/answers.jsonl"
path_training = "../data/pan20-authorship-verification-training-small-truth.jsonl"

In [10]:
answers = pd.read_json(path_answers, lines=True)

In [11]:
truth 

id     value
0     80f5be03-a6af-5a9f-b636-a16ed54af28a  0.999022
1     24518a62-a423-57ae-b5d7-701e9e7c181f  0.993848
2     e85e25f4-4462-51a4-9307-34c53409fdf7  0.008320
3     d54eb4e1-cdfe-52f0-82bc-d0e6de171272  0.004518
4     806c82c1-2433-5f51-81f0-d1e40f3f85e0  0.008332
...                                    ...       ...
9995  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0  0.997531
9996  5b1cc2ef-c300-5430-8f9a-261b003a3617  0.997026
9997  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8  0.941675
9998  a5831896-bb88-562f-b672-e22f3ab73727  0.005273
9999  24f2550f-0d74-5e25-a3ef-398473663394  0.974922

[10000 rows x 2 columns]

In [14]:
truth.id.value_counts()

6941efd1-36ba-5f7e-a487-b8a7f9d66d62    2
042b25c6-9b48-56da-ab27-e36397540572    1
c528e8f4-467a-5234-8d21-572b845bb437    1
323631b4-fc78-5fdb-a2f0-718fb7bc8cda    1
3bcf2202-769e-5299-b40a-396d3b45d6f9    1
                                       ..
525b931f-6a2c-5fb7-b2ee-2b434223cb3c    1
1be9ccf0-13ce-56a0-bd36-e0812bda1b07    1
fd2cf092-9486-5071-8725-dd2d3fce225b    1
0e36c8a9-044c-56de-8318-b2de4c44f0fc    1
d1b69d41-7949-5481-9ef1-6ad8f20279f6    1
Name: id, Length: 9999, dtype: int64

In [17]:
truth.drop_duplicates(subset='id', keep="last",inplace=True)

In [18]:
truth

id     value
0     80f5be03-a6af-5a9f-b636-a16ed54af28a  0.999022
1     24518a62-a423-57ae-b5d7-701e9e7c181f  0.993848
2     e85e25f4-4462-51a4-9307-34c53409fdf7  0.008320
3     d54eb4e1-cdfe-52f0-82bc-d0e6de171272  0.004518
4     806c82c1-2433-5f51-81f0-d1e40f3f85e0  0.008332
...                                    ...       ...
9995  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0  0.997531
9996  5b1cc2ef-c300-5430-8f9a-261b003a3617  0.997026
9997  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8  0.941675
9998  a5831896-bb88-562f-b672-e22f3ab73727  0.005273
9999  24f2550f-0d74-5e25-a3ef-398473663394  0.974922

[9999 rows x 2 columns]

In [29]:
train = pd.read_json(path_training, lines=True)

In [30]:
train

id   same             authors
0      6cced668-6e51-5212-873c-717f2bc91ce6   True  [1446633, 1446633]
1      3c6c188a-db28-59aa-8c09-3d0f799ff579   True  [1446633, 1446633]
2      b0cfa94f-c9ec-5aa5-8331-a5a249b664cf   True  [1446633, 1446633]
3      e6e86e73-9a7b-58f2-a652-a17b4a1bcabf   True  [1446633, 1446633]
4      4fe541af-912e-5a86-81a5-94c6d3891509   True  [1446633, 1446633]
...                                     ...    ...                 ...
52596  3926a1bd-6d33-5513-a694-12d7590443d4  False  [1940652, 4353578]
52597  17227d87-a3cb-5aca-b5fd-bb642e88b030  False  [2581924, 5085069]
52598  0332dcaa-7230-508b-badb-820f9d8eebaa  False  [4819080, 6983686]
52599  f5e4884a-13fd-51fb-a880-053d6655d59a  False  [6070317, 4369540]
52600  900c4a19-e22b-59fd-9cc7-8490919b1696  False  [5412915, 4594479]

[52601 rows x 3 columns]

In [31]:
train.drop_duplicates(subset='id', keep="last",inplace=True)

In [32]:
train

id   same             authors
0      6cced668-6e51-5212-873c-717f2bc91ce6   True  [1446633, 1446633]
1      3c6c188a-db28-59aa-8c09-3d0f799ff579   True  [1446633, 1446633]
2      b0cfa94f-c9ec-5aa5-8331-a5a249b664cf   True  [1446633, 1446633]
3      e6e86e73-9a7b-58f2-a652-a17b4a1bcabf   True  [1446633, 1446633]
4      4fe541af-912e-5a86-81a5-94c6d3891509   True  [1446633, 1446633]
...                                     ...    ...                 ...
52596  3926a1bd-6d33-5513-a694-12d7590443d4  False  [1940652, 4353578]
52597  17227d87-a3cb-5aca-b5fd-bb642e88b030  False  [2581924, 5085069]
52598  0332dcaa-7230-508b-badb-820f9d8eebaa  False  [4819080, 6983686]
52599  f5e4884a-13fd-51fb-a880-053d6655d59a  False  [6070317, 4369540]
52600  900c4a19-e22b-59fd-9cc7-8490919b1696  False  [5412915, 4594479]

[52590 rows x 3 columns]

In [33]:
merged_inner = pd.merge(left=truth, right=train, left_on='id', right_on='id')

In [34]:
merged_inner

id     value   same  \
0     80f5be03-a6af-5a9f-b636-a16ed54af28a  0.999022   True   
1     24518a62-a423-57ae-b5d7-701e9e7c181f  0.993848  False   
2     e85e25f4-4462-51a4-9307-34c53409fdf7  0.008320  False   
3     d54eb4e1-cdfe-52f0-82bc-d0e6de171272  0.004518  False   
4     806c82c1-2433-5f51-81f0-d1e40f3f85e0  0.008332  False   
...                                    ...       ...    ...   
9994  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0  0.997531   True   
9995  5b1cc2ef-c300-5430-8f9a-261b003a3617  0.997026   True   
9996  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8  0.941675   True   
9997  a5831896-bb88-562f-b672-e22f3ab73727  0.005273  False   
9998  24f2550f-0d74-5e25-a3ef-398473663394  0.974922  False   

                 authors  
0     [1543773, 1543773]  
1     [1833652, 5090162]  
2      [208014, 1016753]  
3     [2233151, 3134634]  
4      [832420, 5501874]  
...                  ...  
9994  [4555545, 4555545]  
9995    [396944, 396944]  
9996      [34106, 34106]  
9997  [2084829, 4165982]  
9998    [145100, 598511]  

[9999 rows x 4 columns]

In [36]:
merged_inner = merged_inner.drop(columns=["value"])

In [37]:
merged_inner.to_json("../data/500/truth.jsonl", orient='records', lines=True)

In [38]:
merged_inner

id   same             authors
0     80f5be03-a6af-5a9f-b636-a16ed54af28a   True  [1543773, 1543773]
1     24518a62-a423-57ae-b5d7-701e9e7c181f  False  [1833652, 5090162]
2     e85e25f4-4462-51a4-9307-34c53409fdf7  False   [208014, 1016753]
3     d54eb4e1-cdfe-52f0-82bc-d0e6de171272  False  [2233151, 3134634]
4     806c82c1-2433-5f51-81f0-d1e40f3f85e0  False   [832420, 5501874]
...                                    ...    ...                 ...
9994  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0   True  [4555545, 4555545]
9995  5b1cc2ef-c300-5430-8f9a-261b003a3617   True    [396944, 396944]
9996  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8   True      [34106, 34106]
9997  a5831896-bb88-562f-b672-e22f3ab73727  False  [2084829, 4165982]
9998  24f2550f-0d74-5e25-a3ef-398473663394  False    [145100, 598511]

[9999 rows x 3 columns]

In [ ]:
merged_inner

In [36]:
truth.id.value_counts() > 1

2947eb00-6c85-5947-a9b6-748538d9b0c7     True
067b6207-1c83-5d87-870d-836313ff246c     True
6941efd1-36ba-5f7e-a487-b8a7f9d66d62     True
bd5f4b89-b6ec-577a-8ece-03f22eb081ee     True
5bacf096-61f4-5c1d-9109-9f77cfa58bc1     True
                                        ...  
b1c02d02-eb22-5ba4-b5e1-c3c9e8f35904    False
5b1220fd-32a3-5f0e-aefd-ad4bb7425760    False
fdbcb23b-4a01-5320-ab33-a54ba520a5b0    False
6b5c6b97-e56e-502c-8286-38f4f36a1d66    False
199c62bd-a831-5a57-a9a0-ff21c19fd4f0    False
Name: id, Length: 52590, dtype: bool

In [39]:
df_texts1 = pd.read_json("../data/pairs.jsonl", lines=True)

In [55]:
df_texts1

id  \
0     80f5be03-a6af-5a9f-b636-a16ed54af28a   
1     24518a62-a423-57ae-b5d7-701e9e7c181f   
2     e85e25f4-4462-51a4-9307-34c53409fdf7   
3     d54eb4e1-cdfe-52f0-82bc-d0e6de171272   
4     806c82c1-2433-5f51-81f0-d1e40f3f85e0   
...                                    ...   
9995  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0   
9996  5b1cc2ef-c300-5430-8f9a-261b003a3617   
9997  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8   
9998  a5831896-bb88-562f-b672-e22f3ab73727   
9999  24f2550f-0d74-5e25-a3ef-398473663394   

                                                fandoms  \
0                        [Expendables, Sherlock Holmes]   
1     [Toaru Majutsu no Index/とある魔術の禁書目録, Silence of...   
2                      [Dragon Ball GT, V for Vendetta]   
3                               [She's the Man, Smurfs]   
4                         [Vampire Hunter D, M.I. High]   
...                                                 ...   
9995  [Guardians of the Galaxy, Metal Fight Beyblade...   
9996                           [CSI, NCIS: Los Angeles]   
9997                           [Family Guy, Metal Gear]   
9998  [Bold and the Beautiful, Deadman Wonderland/デッ...   
9999              [Wizard of Oz, Great Mouse Detective]   

                                                   pair  
0     [I gingerly lower myself to the snow beside th...  
1     [As one, the three boys began toward the girls...  
2     [Bulma wanted to convert all their home movies...  
3     [Once she was sure Sebastian wasn"t coming bac...  
4     [Bie was surprised he even answered. He didn"t...  
...                                                 ...  
9995  ["Ronan murdered my wife, Hovet, then my daugh...  
9996  [Rolling over onto his back, he resignedly sur...  
9997  [And then Meg"s eyes rolled into the back of h...  
9998  ["Liam!' Eric stated worryingly, taking one lo...  
9999  [John gathered his laptop case that held his l...  

[10000 rows x 3 columns]

In [40]:
df_texts1.id.value_counts() > 1

6941efd1-36ba-5f7e-a487-b8a7f9d66d62     True
399b9430-9ace-5b24-bd79-6b103b869f8d    False
2f651c46-c151-52dc-9294-3391cc54d452    False
5e5d9eb1-4f5b-57e7-8b73-fccddedf3b48    False
f2f54f42-3800-5c3e-8e8b-23277816fa2d    False
                                        ...  
2ecf9b87-0cf5-5f22-b166-0b888086a526    False
d8a7a5d4-9008-5df1-bb39-bcfc9b7ae80b    False
20fb2105-4b5d-5065-ae01-118110053604    False
43538e77-8dd8-5983-9d6b-f17f79a2795e    False
5236a9d2-40ab-5816-ab97-a34af32b6ad9    False
Name: id, Length: 9999, dtype: bool

In [41]:
merged_inner = pd.merge(left=df_texts1, right=truth, left_on='id', right_on='id')
# In this case `species_id` is the only column name in  both dataframes, so if we skipped `left_on`
# And `right_on` arguments we would still get the same result

# What's the size of the output data?
merged_inner.shape
merged_inner

id  \
0      80f5be03-a6af-5a9f-b636-a16ed54af28a   
1      24518a62-a423-57ae-b5d7-701e9e7c181f   
2      e85e25f4-4462-51a4-9307-34c53409fdf7   
3      d54eb4e1-cdfe-52f0-82bc-d0e6de171272   
4      806c82c1-2433-5f51-81f0-d1e40f3f85e0   
...                                     ...   
10000  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0   
10001  5b1cc2ef-c300-5430-8f9a-261b003a3617   
10002  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8   
10003  a5831896-bb88-562f-b672-e22f3ab73727   
10004  24f2550f-0d74-5e25-a3ef-398473663394   

                                                 fandoms  \
0                         [Expendables, Sherlock Holmes]   
1      [Toaru Majutsu no Index/とある魔術の禁書目録, Silence of...   
2                       [Dragon Ball GT, V for Vendetta]   
3                                [She's the Man, Smurfs]   
4                          [Vampire Hunter D, M.I. High]   
...                                                  ...   
10000  [Guardians of the Galaxy, Metal Fight Beyblade...   
10001                           [CSI, NCIS: Los Angeles]   
10002                           [Family Guy, Metal Gear]   
10003  [Bold and the Beautiful, Deadman Wonderland/デッ...   
10004              [Wizard of Oz, Great Mouse Detective]   

                                                    pair   same  \
0      [I gingerly lower myself to the snow beside th...   True   
1      [As one, the three boys began toward the girls...  False   
2      [Bulma wanted to convert all their home movies...  False   
3      [Once she was sure Sebastian wasn"t coming bac...  False   
4      [Bie was surprised he even answered. He didn"t...  False   
...                                                  ...    ...   
10000  ["Ronan murdered my wife, Hovet, then my daugh...   True   
10001  [Rolling over onto his back, he resignedly sur...   True   
10002  [And then Meg"s eyes rolled into the back of h...   True   
10003  ["Liam!' Eric stated worryingly, taking one lo...  False   
10004  [John gathered his laptop case that held his l...  False   

                  authors  
0      [1543773, 1543773]  
1      [1833652, 5090162]  
2       [208014, 1016753]  
3      [2233151, 3134634]  
4       [832420, 5501874]  
...                   ...  
10000  [4555545, 4555545]  
10001    [396944, 396944]  
10002      [34106, 34106]  
10003  [2084829, 4165982]  
10004    [145100, 598511]  

[10005 rows x 5 columns]

In [42]:
merged_inner.drop(columns=['fandoms','pair'])

id   same             authors
0      80f5be03-a6af-5a9f-b636-a16ed54af28a   True  [1543773, 1543773]
1      24518a62-a423-57ae-b5d7-701e9e7c181f  False  [1833652, 5090162]
2      e85e25f4-4462-51a4-9307-34c53409fdf7  False   [208014, 1016753]
3      d54eb4e1-cdfe-52f0-82bc-d0e6de171272  False  [2233151, 3134634]
4      806c82c1-2433-5f51-81f0-d1e40f3f85e0  False   [832420, 5501874]
...                                     ...    ...                 ...
10000  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0   True  [4555545, 4555545]
10001  5b1cc2ef-c300-5430-8f9a-261b003a3617   True    [396944, 396944]
10002  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8   True      [34106, 34106]
10003  a5831896-bb88-562f-b672-e22f3ab73727  False  [2084829, 4165982]
10004  24f2550f-0d74-5e25-a3ef-398473663394  False    [145100, 598511]

[10005 rows x 3 columns]

In [46]:
merged_inner[merged_inner.id.map(merged_inner.id.value_counts() > 1)]

id  \
1248  6941efd1-36ba-5f7e-a487-b8a7f9d66d62   
1249  6941efd1-36ba-5f7e-a487-b8a7f9d66d62   
1250  6941efd1-36ba-5f7e-a487-b8a7f9d66d62   
1251  6941efd1-36ba-5f7e-a487-b8a7f9d66d62   
5551  197862fd-4763-5cbd-9493-db84c3f5e090   
5552  197862fd-4763-5cbd-9493-db84c3f5e090   
6479  067b6207-1c83-5d87-870d-836313ff246c   
6480  067b6207-1c83-5d87-870d-836313ff246c   
7610  2947eb00-6c85-5947-a9b6-748538d9b0c7   
7611  2947eb00-6c85-5947-a9b6-748538d9b0c7   

                                           fandoms  \
1248  [Star Trek: 2009, Star Wars: The Clone Wars]   
1249  [Star Trek: 2009, Star Wars: The Clone Wars]   
1250                  [Star Trek: 2009, Star Wars]   
1251                  [Star Trek: 2009, Star Wars]   
5551    [A song of Ice and Fire, Mystic Messenger]   
5552    [A song of Ice and Fire, Mystic Messenger]   
6479    [Chronicles of Vladimir Tod, Supernatural]   
6480    [Chronicles of Vladimir Tod, Supernatural]   
7610                     [Blue Heelers, Torchwood]   
7611                     [Blue Heelers, Torchwood]   

                                                   pair  same  \
1248  [Pike let out a snort of laughter. "Sure. Earn...  True   
1249  [Pike let out a snort of laughter. "Sure. Earn...  True   
1250  [Pike let out a snort of laughter. "Sure. Earn...  True   
1251  [Pike let out a snort of laughter. "Sure. Earn...  True   
5551  ["I"m just as confused by this place as you ar...  True   
5552  ["I"m just as confused by this place as you ar...  True   
6479  [Vlad sent a small smile to Dorian"s questioni...  True   
6480  [Vlad sent a small smile to Dorian"s questioni...  True   
7610  [Dr. Hannah grinned and gave her an encouragin...  True   
7611  [Dr. Hannah grinned and gave her an encouragin...  True   

                 authors  
1248  [2943978, 2943978]  
1249  [2943978, 2943978]  
1250  [2943978, 2943978]  
1251  [2943978, 2943978]  
5551    [748687, 748687]  
5552    [748687, 748687]  
6479  [2322840, 2322840]  
6480  [2322840, 2322840]  
7610    [702614, 702614]  
7611    [702614, 702614]

In [48]:
merged_inner

id  \
0      80f5be03-a6af-5a9f-b636-a16ed54af28a   
1      24518a62-a423-57ae-b5d7-701e9e7c181f   
2      e85e25f4-4462-51a4-9307-34c53409fdf7   
3      d54eb4e1-cdfe-52f0-82bc-d0e6de171272   
4      806c82c1-2433-5f51-81f0-d1e40f3f85e0   
...                                     ...   
10000  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0   
10001  5b1cc2ef-c300-5430-8f9a-261b003a3617   
10002  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8   
10003  a5831896-bb88-562f-b672-e22f3ab73727   
10004  24f2550f-0d74-5e25-a3ef-398473663394   

                                                 fandoms  \
0                         [Expendables, Sherlock Holmes]   
1      [Toaru Majutsu no Index/とある魔術の禁書目録, Silence of...   
2                       [Dragon Ball GT, V for Vendetta]   
3                                [She's the Man, Smurfs]   
4                          [Vampire Hunter D, M.I. High]   
...                                                  ...   
10000  [Guardians of the Galaxy, Metal Fight Beyblade...   
10001                           [CSI, NCIS: Los Angeles]   
10002                           [Family Guy, Metal Gear]   
10003  [Bold and the Beautiful, Deadman Wonderland/デッ...   
10004              [Wizard of Oz, Great Mouse Detective]   

                                                    pair   same  \
0      [I gingerly lower myself to the snow beside th...   True   
1      [As one, the three boys began toward the girls...  False   
2      [Bulma wanted to convert all their home movies...  False   
3      [Once she was sure Sebastian wasn"t coming bac...  False   
4      [Bie was surprised he even answered. He didn"t...  False   
...                                                  ...    ...   
10000  ["Ronan murdered my wife, Hovet, then my daugh...   True   
10001  [Rolling over onto his back, he resignedly sur...   True   
10002  [And then Meg"s eyes rolled into the back of h...   True   
10003  ["Liam!' Eric stated worryingly, taking one lo...  False   
10004  [John gathered his laptop case that held his l...  False   

                  authors  
0      [1543773, 1543773]  
1      [1833652, 5090162]  
2       [208014, 1016753]  
3      [2233151, 3134634]  
4       [832420, 5501874]  
...                   ...  
10000  [4555545, 4555545]  
10001    [396944, 396944]  
10002      [34106, 34106]  
10003  [2084829, 4165982]  
10004    [145100, 598511]  

[10005 rows x 5 columns]

In [49]:
merged_inner.drop_duplicates(subset='id', keep="last",inplace=True)

In [52]:
merged_inner.drop(inplace=True, columns=['fandoms','pair'])

In [53]:
merged_inner.to_json("../data/model/truth.jsonl", orient='records', lines=True)

In [54]:
merged_inner

id   same             authors
0      80f5be03-a6af-5a9f-b636-a16ed54af28a   True  [1543773, 1543773]
1      24518a62-a423-57ae-b5d7-701e9e7c181f  False  [1833652, 5090162]
2      e85e25f4-4462-51a4-9307-34c53409fdf7  False   [208014, 1016753]
3      d54eb4e1-cdfe-52f0-82bc-d0e6de171272  False  [2233151, 3134634]
4      806c82c1-2433-5f51-81f0-d1e40f3f85e0  False   [832420, 5501874]
...                                     ...    ...                 ...
10000  28b2181e-d5ad-57ae-b1bd-13ecf49c8dd0   True  [4555545, 4555545]
10001  5b1cc2ef-c300-5430-8f9a-261b003a3617   True    [396944, 396944]
10002  0f75d76c-51ba-5f99-94b9-ab68dab8f3b8   True      [34106, 34106]
10003  a5831896-bb88-562f-b672-e22f3ab73727  False  [2084829, 4165982]
10004  24f2550f-0d74-5e25-a3ef-398473663394  False    [145100, 598511]

[9999 rows x 3 columns]

In [11]:
def label(res):
    if res ==False:
        return 0.0
    elif res == True:
        return 1.0

In [12]:
def rounded(res):
    return np.round(res['value'])
    

In [13]:
merged_inner['label'] = merged_inner.same.apply(label)

In [14]:
merged_inner['result'] = np.round(merged_inner['value'])

In [15]:
np.sum(merged_inner['label'] == merged_inner['result'])

9642

In [ ]:
corpus = [
    "Hello!. Your are the best, don't you ? .",
    "Lou Reed is the best.",
    "I like Python (data scientist), Java (Programming) and C."
    
    
]

In [ ]:
corpus = [
    "1234567 ABCDEF G ZX"
   
]

In [ ]:
vectorizer = TfidfVectorizer(analyzer='char_wb', min_df=0.1, vocabulary=None, norm='l1', ngram_range=(1, 6))

In [ ]:
X = vectorizer.fit_transform(corpus)

In [ ]:
vectorizer.get_feature_names()

In [ ]:
dense = X.toarray()

In [ ]:
dense

In [ ]:
vectorizer = TfidfVectorizer(max_features=3000, analyzer='char',
                                 ngram_range=(4, 4))

In [ ]:
vectorizer.fit(corpus)

In [ ]:
transform = vectorizer.transform(corpus)

In [ ]:
dense = transform.toarray()

In [ ]:
dense.shape

In [ ]:
vectorizer.get_feature_names()